### ISSUE TITLE
Error when trying to import lcviz and problems with visualising the data-points on the graph

### ISSUE THREAD

**Issue by eggulbahar** [spacetelescope/lcviz#116]
I have been using lcviz to plot my lightcurves produces using XMM-Newton data and encountered two main issues whilst working.

- I have been having issues when trying to import lcviz. I have been working on a JupyterLab environment with version 3.5.0. When I simply write `import lcviz` I get an error saying `AttributeError: module 'mistune' has no attribute 'BlockGrammar'` (see images). However, when I re-run the same kernel the error completely disappears and lcviz is imported successfully. I do not know if this is an error that I get only, but I thought I should raise it with you.

![image](https://github.com/spacetelescope/lcviz/assets/100635499/8685598a-ef1e-455f-870c-e126733b5f7e)
![image](https://github.com/spacetelescope/lcviz/assets/100635499/2439dba0-ee2d-41da-93af-98f23000c19f)

- When plotting the interactive graph the output I get is just an empty screen, showing no data-points, however, again when I re-run the kernel everything plots normally and I can see the data-points on the interactive output. However, then I have issues with the subset selection colouring. I have noticed that when selecting even numbered subsets the range that was selected is not coloured, while the odd numbered ones are.

I thank you in advance for your answer and thank you for the great tool! :)

**Comment by kecnry** [comment]
Thanks for posting these - I have not seen either the `mistune` or subset bugs before, but have seen the occasional empty viewers (likely an upstream bug) that we have been trying to track down.  As you noticed, it just randomly happens and restarting usually makes it go away - although that isn't always convenient.

For the `mistune` one: what version of voila do you have (`import voila, print(voila.__version__)`)?

For the subsets: does this happen immediately on creating the subset?  If you run the following snippet to start lcviz and then immediately draw subsets, do you see something different than below?

```
from lightkurve import search_lightcurve
from lcviz import LCviz

lc = search_lightcurve("HAT-P-11", mission="Kepler", cadence="long", quarter=10).download() #.flatten()

lcviz = LCviz()
lcviz.load_data(lc)
lcviz.show()
```

https://github.com/spacetelescope/lcviz/assets/877591/396858f0-abd5-4fb9-9a1a-6d7c86b6c057

**Comment by eggulbahar** [comment]
Thank you for the reply! 
So, when I try to import voila, I get the same error , which this time does not go away if a re-run the kernel:
![image](https://github.com/spacetelescope/lcviz/assets/100635499/572430e9-0bc7-4065-8a65-09e43b4c1e25)
When I use pip show to see it's version this is what I get though:
![image](https://github.com/spacetelescope/lcviz/assets/100635499/9880c372-cd8d-4939-87e1-9f43de00b3c6)

About the subset selection error, I have noticed that this has gone, I assume it was fixed on your end? as I didn't do anything on mine :)

Many thanks!

**Comment by kecnry** [comment]
Thanks for the updates.  Looks like the voila issue might be a version conflict between nbconvert and mistune (see [nbconvert#1864](https://www.github.com/jupyter/nbconvert/issues/1864)).  There are a few different suggestions in that thread for upgrading/downgrading those two dependencies to get rid of the problem - if those don't work or this keeps happening on a fresh install, we can consider setting specific version requirements of those two packages from lcviz, but other than that, I unfortunately don't think there is much that can be done.
