### ISSUE TITLE
phasing incorrect immediately after phase-viewer creation

### ISSUE THREAD

**Issue by duytnguyendtn** [spacetelescope/lcviz#25]
Found during my review of #22, the mouseover seems to track invisible data points that *might* be of a different period:

![image](https://github.com/spacetelescope/lcviz/assets/25206008/435cfb76-d1ae-45f3-b039-139e36b0305b)

After changing the period to "redraw" the points, the mouseover tracks properly

**Comment by kecnry** [comment]
I have not seen or heard of this happening recently so am going to assume that this was fixed by #19 or other recent simplifications of the code.  If it shows up again, we can always reopen.
