### ISSUE TITLE
feature request: skip the color cycler in Flatten

### ISSUE THREAD

**Issue by bmorris3** [spacetelescope/lcviz#31]
The Flatten plugin can overwrite a dataset with the flattened LC. Since LCviz loads the flattened LC as a new data entry, we could (should?) suppress the auto-increment of the color cycler for this operation.

**Comment by kecnry** [comment]
Won't https://github.com/spacetelescope/jdaviz/pull/2288 cover this case?

**Comment by kecnry** [comment]
Seems that the color is now preserved, closing as fixed by https://github.com/spacetelescope/jdaviz/pull/2288
