### ISSUE TITLE
tests failing with jdaviz main

### ISSUE THREAD

**Issue by kecnry** [spacetelescope/lcviz#92]
devdeps tests are recently failing in PRs with jdaviz main for viewers and markers.  It's unclear whether this change is expected and needs to be fixed here or is a sign of a bug in jdaviz that has been introduced but not caught by upstream test coverage.

**Comment by pllim** [comment]
```
lcviz/tests/test_plugin_markers.py::test_plugin_markers -
AssertionError: assert ('Cursor 0.00... 1.00497e+00') == ('Cursor 0.00... 9.67587e-01')
  
  At index 1 diff: 'Time 0.00000e+00 d' != 'Time 5.45833e+00 d'
  
  Full diff:
    (
        'Cursor 0.00000e+00, 0.00000e+00',
  -     'Time 5.45833e+00 d',
  ?           ^ ^^^^^
  +     'Time 0.00000e+00 d',
  ?           ^ ^^^^^
  -     'Flux 9.67587e-01',
  +     'Flux 1.00497e+00',
    )
FAILED lcviz/tests/test_viewers.py::test_reset_limits - assert 0.9675873265993092 == 0.0
```

Why does this look familiar. Didn't you change how the viewer limits work recently, Kyle?

If you cannot remember a bisect of Jdaviz `main` would be your best bet.

**Comment by kecnry** [comment]
It should not, this test is for a scatter (light curve) viewer

**Comment by kecnry** [comment]
Fixed by https://github.com/kecnry/lcviz/pull/8 for jdaviz 3.9 and #102 for lcviz main (to avoid testing with jdaviz 3.9 in devdeps)
